settings:
  orchestrator.sagemaker:
    synchronous: false

parameters:
  # author_links are loaded from configs/digital_data_etl_ai_architect.yaml in tools/run.py.
  # Generate instruct dataset pipeline parameters
  test_split_size: 0.1
  push_to_huggingface: false
  dataset_id: dimension-drifter/instruct-dataset
  mock: false
